### PR TITLE
Fix GitHub license autodetect

### PR DESCRIPTION
**Pull request by maoo**
I've renamed `LICENSE_HEADER` to `FILE_HEADER` and `add-license-headers.bat` to `add-file-headers.bat`. Now `Apache-2.0` shows on the top right of https://github.com/maoo/plexus-interop page.

### CODE REVIEW

**Comment by udalmik** [comment]
I think deleted file references in .net build script, see [build ](https://ci.appveyor.com/project/finos-admin/plexus-interop/builds/32245232) failing with following:
`
File 'C:\projects\plexus-interop\LICENSE_HEADER' specified for property 'header' does not exist.
`

**Comment by maoo** [comment]
> I think deleted file referenced in .net build script, see [build ](https://ci.appveyor.com/project/finos-admin/plexus-interop/builds/32245232) failing with following:
> `File 'C:\projects\plexus-interop\LICENSE_HEADER' specified for property 'header' does not exist.`

TY @udalmik ! Is the `LICENSE_HEADER` mentioned somewhere, or it's a .NET naming convention?

**Comment by udalmik** [comment]
@maoo, it is just referenced from [few more Gradle scripts](https://github.com/finos-plexus/plexus-interop/search?q=LICENSE_HEADER&unscoped_q=LICENSE_HEADER), "copy/paste effect" I suppose :)

**Comment by maoo** [comment]
@udalmik - PR updated, the build seems happier now.

**Pull request merged**
