### PR TITLE
add end of terms conditions for license detection

### PR DESCRIPTION
**Pull request by brntbeer**
@maoo @mcleo-d I think this may be why the license won't be accepted. It's missing pieces.

Can you or anyone else in this repo update the pieces in this license that are missing like name of owner and stuff?

related : https://github.com/finos/open-developer-platform/issues/47

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your pull request and welcome to our community! We require contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) and we don't seem to have CLAs on file for these contributors to the Pull Request: (@brntbeer). In order for your PR to be reviewed and merged, please follow the directions at the link above.

Project team: please **do not merge this Pull Request** until Foundation staff have confirmed that a CLA is in place for the new contributor(s) listed above.

If there are any questions, please don't hesitate to [get in touch with our Infrastructure Support team](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/77955298/Getting+in+Touch#GettinginTouch-InfrastructureSupport). /CC @finos-admin

**Comment by brntbeer** [comment]
Also i dont think im allowed by employment to submit this CLA so feel free to close this out. All i did was copy the auto generated license from choosealicense.org https://choosealicense.com/licenses/apache-2.0/

**Comment by mcleo-d** [comment]
Hi @udalmik - I'd like to introduce you to @brntbeer from GitHub who's helping us diagnose and fix the following Open Developer Platform issue ... 

related : https://github.com/finos/open-developer-platform/issues/47

Are you able to work with @brntbeer and @maoo to help fix?

Kind regards,

James.

**Comment by maoo** [comment]
Thanks @brntbeer , well spotted and thanks SO much for your contribution! I just checked our template on https://github.com/finos/project-blueprint/blob/master/LICENSE and you're right!

Re. CLA, it's totally safe to merge this PR, given that fixing a license doesn't entitle any intellectual property . @udalmik , feel free to merge this PR . Also, we're working on getting a CCLA signed with GitHub, should be a matter of days.

**Comment by udalmik** [comment]
Cool, I'll merge this one and raise one more on top to update year/organization placeholders.

**Comment by maoo** [comment]
@udalmik - I see that the license still doesn't show as `Apache 2.0` on GitHub, see screenshot.

Screenshot 2020-03-29 at 00 02 13

I see that you haven't updated the copyright on https://github.com/finos-plexus/plexus-interop/blob/master/LICENSE#L189 , could you please set it to `Copyright 2017-2019 Plexus Interop Deutsche Bank AG`, as stated in the `NOTICE` file?

Thanks!

**Pull request merged**
